### ISSUE TITLE
Create unit tests for managers

### ISSUE THREAD

**Issue by Lameorc** [Lameorc/pb138_RestaurantMenu#2]
There should be some tests to check the functionality of entity managers outside of live data.

**Comment by jochec** [comment]
Created MenuManager tests based on FoodManager tests. Not passing - seems like assertj field-by-field comparation compares even id, which cause most of the errors.

Also maybe we should drop database after tests, because I'm getting some errors, that tables already exists...

**Comment by Lameorc** [comment]
The tables should be dropped in the FoodManager tests. I might have marked the memory database object as final, which might be causing problems. The field by field comparision is working as it should be, comparing all the fields. The CreateFood/Menu function should assign id to the object which is passed to them, this seems to not be working. I will have a look at it

**Comment by Lameorc** [comment]
I've looke at it and the error with tables already exisitng was not cause by them not being dropped but by wrong before method. The one used was from assertJ while the rest of the tests was written with testng. The test now seem to work fine. The managers still need to be fixed however
